x=float(input("enter the number of fresh bread purchased:"))
y=float(input("enter the number of old day bread purchased:"))
print("regular price:185.00")
print("amount of fresh bread:",x*185.0)
print("amount of old day bread:",y*185*0.4)
print("total amount:",x*185.0+y*185*0.4)
